DECLARE
  P_TIPODOC VARCHAR2(200);
  P_NUMDOC VARCHAR2(200);
  P_TIPOBENEFICIO VARCHAR2(200);
  C_CURSOR SYS_REFCURSOR;
BEGIN
  P_TIPODOC := 'DNI';
  P_NUMDOC := '12345678';
  P_TIPOBENEFICIO := NULL;

  MP_P_LISTAR_BENEFICIOS_MPE(
    P_TIPODOC => P_TIPODOC,
    P_NUMDOC => P_NUMDOC,
    P_TIPOBENEFICIO => P_TIPOBENEFICIO,
    C_CURSOR => C_CURSOR
  );
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('C_CURSOR = ' || C_CURSOR);
*/ 
  :C_CURSOR := C_CURSOR; --<-- Cursor
--rollback; 
END;
