SET SERVEROUTPUT ON;

CREATE OR REPLACE FUNCTION PROXIMO_ANIVERSARIO 
(
  ID_CLIENTE IN NUMBER 
) RETURN DATE 
IS
    FECHA_ANIVERSARIO DATE;
BEGIN
  
  SELECT ADD_MONTHS(CREADO, 12) INTO FECHA_ANIVERSARIO FROM CLIENTES WHERE ID = ID_CLIENTE;
  
  RETURN FECHA_ANIVERSARIO;
  
END PROXIMO_ANIVERSARIO;




SELECT PROXIMO_ANIVERSARIO(1) FROM CLIENTES;
EXEC PRIMER_CLIENTE();
